version: '2'
services:
  ftp:
    build: ./ftpd
    image: will/ftp
    ports: 
      - "21:21"
      - "30000-30009:30000-30009"
    volumes:
      - /data/www:/home/folkatronic
      - /data/logs:/home/folkatronic/logs:ro
      - /etc/pure-ftpd/pure-pw:/etc/pure-ftpd/passwd:ro # For FTP user-account passwd file
    environment:
      - PUBLICHOST=folkatronic.com
  webserver:
    build: ./apache-php
    image: will/apache-php
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /data/logs/apache2:/var/log/apache2 # Logs
      - /data/www:/var/www/html # Webserve root
      - /etc/letsencrypt/:/etc/ssl/ # SSL Certs and Keys
    links:
      - database
  database:
    image: mysql/mysql-server:5.7
    volumes:
      - /home/will/.keys/sql.txt:/tmp/password.txt
      - /data/db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=/tmp/password.txt
      - MYSQL_ONETIME_PASSWORD=yes
